version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    build:
      context: ./app
      args:
        - nextcloud_subdomain=${SUBDOMAIN_NEXTCLOUD}
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  nextcloud:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-tier
      - default
    depends_on:
      - app

  cron:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code
    restart: always
    expose:
      - 9980
    cap_add:
      - MKNOD
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - domain=${DOMAIN_COLLABORA}
      - dictionaries=${DICTIONARIES_COLLABORA}
      - username=${USERNAME_COLLABORA}
      - password=${PASSWORD_COLLABORA}
    networks:
      - proxy-tier

  letsencrypt:
    build:
      context: ./proxy
      args:
        dns_cloudflare_email: ${CLOUDFLARE_EMAIL}
        dns_cloudflare_api_key: ${CLOUDFLARE_API}
    restart: always
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - leconfig:/config
    environment:
      - PGID=${DOCKER_PGID}
      - PUID=${DOCKER_PUID}
      - EMAIL=${LE_EMAIL}
      - URL=${LE_URL}
      - SUBDOMAINS=${LE_SUBDOMAINS}
      - ONLY_SUBDOMAINS=${LE_ONLY_SUBDOMAINS}
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - STAGING=${LE_STAGING}
      - TZ=${LE_TZ}
    networks:
      - proxy-tier

  # signal-web-gateway:
  #   image: registry.gitlab.com/morph027/signal-web-gateway:master
  #   restart: always
  #   expose:
  #     - 5000
  #   volumes:
  #     - signal:/signal
  #     - /etc/localtime:/etc/localtime:ro

  cloudflare-ddns:
    image: joshava/cloudflare-ddns
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZONE=${CLOUDFLARE_ZONE}
      - HOST=${CLOUDFLARE_HOST}
      - EMAIL=${CLOUDFLARE_EMAIL}
      - API=${CLOUDFLARE_API}
      - TTL=1
      - PROXY=false

volumes:
  db:
  nextcloud:
  leconfig:
  signal:

networks:
  proxy-tier:
